The Q_DECLARE_METATYPE(DataEngine*) was added to the "Plasma/Service" header.
Fix
        error: redefinition of 'struct QMetaTypeId<Plasma::Service*>'
        error: redefinition of 'struct QMetaTypeId<Plasma::ServiceJob*

This "Plasma/Service" change was a source incompatible change but i leave it to
more capable minds to consider if it is acceptable. I have no clue.

CCMAIL: kde-devel@kde.org
CCMAIL: amarok-devel@kde.org
CCMAIL: aseigo@kde.org