Revert "Fix compilation, inject missing metatype declaration"
this breaks compilation with qt4.5! error is this:
/home/leo/build/amarok-build/src/scriptengine/generator/generator/generated_cpp/com_trolltech_qt_gui/qtscript_QTextCodecPlugin.cpp:61: error: redefinition of ‘struct QMetaTypeId<QList<int> >’
/home/leo/build/amarok-build/src/scriptengine/generator/generator/generated_cpp/com_trolltech_qt_gui/qtscript_QTextCodecPlugin.cpp:58: error: previous definition of ‘struct QMetaTypeId<QList<int> >

This reverts commit 22f65daac6bf9c73d4fa0634e7a17067f90c695e.

svn path=/trunk/extragear/multimedia/amarok/; revision=926163