Fix metainfo generation for Amarok applets
Summary:
Cmake reports the following error when processing metadata.desktop file for Amarok's applets: lyrics, analyzer, wikipedia, etc.

```
  Error: description missing, will result in broken appdata field as
  <sumary/> is mandatory at
  /amarok/src/context/applets/albums/package/metadata.desktop
```
The error is because such .desktop files do not have a  "Comment=" field. I have added such to all files

Test Plan: Run cmake and see that the error is not preset.

Reviewers: #amarok, amarok-devel, heikobecker

Reviewed By: heikobecker

Subscribers: heikobecker, #amarok, amarok-devel

Differential Revision: https://phabricator.kde.org/D27370