Revert "This seems to make Amarok work without needing the embedded database -- at least to the point where you can select the new DB without it crashing"
This reverts commit cb65254d7ab17b3d7e690e45a3ded576bbf3b2ee.

Sorry, this broke MySQL Embedded support. Error message was this:
"/usr/bin/ld: /home/mark/usr/lib/mysql/libmysqlclient.a(my_compress.o): in function my_compress_alloc:my_compress.c:71: error: undefined reference to 'compress'"